sudo: required

env:
  global:
  - REPO=valentineg/basic-auth-ws
  - secure: "L6ixnpq36b1D2EQGqa+0If0FzaqZLvYmQISuPBwYZcdhnnbD6/rtxdDqfPc4q+06Brnxg4b2MyHZTbsKTMjc5Cn7t+5/l6PpmU2NIH+85KPSct6+D0VuRZSZpRUhdz/BYryprJ7tLrl3rJluDG5Gn5Quru3qCL+EzODV4EIf7VeCQSLe1TpbufVc7LNZ7R40C61qIDTD33XxVIqoUlyMVo69IRCAEuc2l8GYulOXfv9LKNBUcnzjOCI9zGTrYy2Hlg1edaRPgbu34/IQQotAw4ioY+eHjoXal9Xodx8TICO1WbWaVND0CssFwC94m8MgWiAkO6LPPmwwqsVsb0YMawEBrtnNYt5NQhQMjnWcSmeUIyhdyJEOjJ6k3PYWon5ZDcyLSVE5vmrZEVb8qN6sZg5/aPHXradfMTTrIYxgY2nBbyaxP28ZImfOS2ocY/h1N7KqIaW2IuAo9O4SjJNTs4QcFJCp3b9VU21+lGrCBohu7TOQXlxdGGzH69lib2l7bw98IhXmvtevCklkuiq/PMo5Do7CnLKPaPMVczY/1HvKw1pcj75gM0gi07UBveu9jDfVJuO5nG9j7Rn+M4+A0EFf/Eacf3K0IuQLcq29uwjOfwgRc6ZpCzKiKF2jFFnY4NSX7mfELgu7oWTPiW0L8VpUlZy+NB103RC1h+8ZDqI="
  - secure: "F+Ww6p+O6RtBDgjqRAct4a93IzsjELJkWqRBoAomEsEUGFiUIAXylshD6Ky+tj0kXUvK51IWV3Ti8cU/FwNq52SreT4g4zGVgkI+GgbxyUZ8jd8yh0TIpB0/gnAu8TqJ2XsnuP49L64CQ754pph7OIMCZa0cEkRBfr2lrxuYKxCV+Wa1LItSHZZTOF7T/q/b+OcRrfL7SsdOnPAL/nti+kW6vMyp/iwkOCZFxIeuI9qIdhOQ/mmjIbabiyetrdSlvyByr4zxickycBZj9QKByXDABu/kJqqh7t3DrDt2m1R8Pf8lFEZXuuvGFNvmfu4ifxLipiYeCye2virXibsO2xhqUff0wAmFLP19y1hK/nCPF0MW+zcdE/+QcH30bdfo+3zNH5Pox0ujZBsjWgKwy4+S7tqB5HGoKRDunWqX/0MJrr7wzJgMNnBz7/iEz5VivLlej2eG9X1ACL87DA4I33jWP+Uz7tUsgG5c6iZcxaOeux9/hrAq0bhaSqnb/O+5QN+RFVeexAI8xkKQVBiUu0wWE/5BvEIT2+kfQGWEMvAgXN+5ldfCfz4MHLyCPSc5CETTl+53Bv1QHHljB3+uG2iU0nfU0GzGoSMzP3WSQ0sk1+GF3MuS0qobSsy4daBLtIBEotNJzwVGfqwpeCI4m/FZcchtN9AzV5Tny/LmZIQ="

language: node_js
node_js:
  - "lts/*"

services:
  - docker

script:
  - docker build -t $REPO .
  - docker run -dit -p 80:8080 $REPO
  - sleep 3
  - docker ps -a
  - curl http://127.0.0.1/auth -d '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:mat="http://maths.lenin.com"><soapenv:Header/><soapenv:Body><mat:up><mat:user>user</mat:user><mat:pass>pass</mat:pass></mat:up></soapenv:Body></soapenv:Envelope>' | grep 'authres'

after_success:
  - docker images
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u $DOCKER_USER -p $DOCKER_PASS;
    docker push $REPO;
    fi

deploy:
  provider: heroku
  api_key:
    secure: "oDTYwPqnhFZEKFQLdRN4hJQBDsqphrPR/1tdKob8eJMYHCOoIwz7zU/jIgDbL/uZpgftQg+jpQ8PHQusfvGx///KtIpiO3ZIIYMV8nuK710C+Y5Se5LSJCS5KVmlbXmD0MC28NLXmewREqMJA0VI3GYV6CRbho8Zfw0+RmDiMJ2ZRis6iVDn24Gk8oIQfYHzL0Td8wgdP68L0FgejAOOIyt9eWEXnPZoyY7L8yzpkE9JgjpYh4puZMDbmq/B2P1lr/Yee+QcyNxSy7uoLVIgXcCs1u/A8v9avV1ksPjQ3LAOkfU/5WqJ1ZCeGii0TrvzAMCBzn3FiJwgD5kXO3Q9EqkhPzf1+ZX6djFD0IoyNzrmQIbFrLiONA52kfwpEBr+vf2rGAfUK3W+3rB/bwANTnVtTKVh7lNZOZmXHCGEcLOIpJqOaPsBxYJmObNDR6yGStYC6Ig448Jy+YSMvFvGbhDz4380RCbbJt5lMjwgNXHeD1Z4GeE+WqEDdfaDFq3dVZC+bO+y8QL5gFqi1HI0k/NBBCNFG1MygUh4/1WWA1Lryqe1YrEV8dY3ImO76uUHn3T6YaxFlyyGxNcpWYq75NOiT381Ze4X0EKbwHzlehFoJBUP89yQQVpSC2ksBSTDQwRaL2fKanvT5u93gwknOjyMVOjw8TG9NkuPCp0159s="
  app: basic-auth-ws
  
notifications:
  slack:
    secure: O0NIV94dxLyyLigr032VEgxEdIFna0P2/ev8SlK15E8syaBxoLe/lSZb1Icwb/QsqA3JSWFywY3gS1YtNVteVkUcc+dHpP+x26iQbo6OTyR25sA8xqqNam9i7wu7zAIkXU02KHQajuu09rHDLk2S/XkhtJVsvjcLW7Ot8lrgXadtLidC0KlMJs9m/KIl1j62eOSz3ycjWSFzMuZluOZ0DvqksNdj1x3hh5KZsJez7n/L5dPyHr9/8QuvizJvhsHAgapfXXm0FjO9w7NRNplCy85zTk6QDxT+7/Pv4B0XMaZAsm5KZI4wF99QZudBH1B2VmKDYpggBNwebglb/cCY2s85RNGCky4ujRoifZgvGewJaGtwxtT7FllUJJTVZbdIKTHSlI03xGeBBXqXQaNsbhZ3oXoQIm7N8qIeBCcEkJBoTmF+y+OPml4rnwWPCnSacOXdPFWqpKhLm9ONZzWQfnp9hWG6gYOZv20tTmv6+IIIzCnvdFOpEgn0X55iavSk9j3Fc70AUtzY9UlAvGJRrChReIUtVGy+kvpWx0osp1bhb+i1mtjSx+BeGiIH7Awr23Bc69knz2b39zKYxzszRfkXa/HKyg2guFT6bdhHKbn+kAn2s+EfFDotMBmBfPQ5rJQWoarCBUNRQPeodx32o/o83stOH+1KXtZwz/s9nBo=
